#version 430 core

layout (local_size_x=1) in;

uniform sampler2D point0;
uniform sampler2D point1;
uniform sampler2D point2;
uniform sampler2D intersection;

layout (std430, binding = 1) buffer outBuffer
{
    vec4 v[];
};

layout (location=1) uniform int inputSize;

void main()
{
    vec2 texCoord = vec2(0.5f, 0.5f);

    v[0] = texture(point0, texCoord);
    v[1] = texture(point1, texCoord);
    v[2] = texture(point2, texCoord);
    v[3] = texture(intersection, texCoord);
}
